namespace PMC
{
    public enum FaceBlendShapes
    {
        Neutral = 0,
        BrowDownLeft = 1,
        BrowDownRight = 2,
        BrowInnerUp = 3,
        BrowOuterUpLeft = 4,
        BrowOuterUpRight = 5,
        CheekPuff = 6,
        CheekSquintLeft = 7,
        CheekSquintRight = 8,
        EyeBlinkLeft = 9,
        EyeBlinkRight = 10,
        EyeLookDownLeft = 11,
        EyeLookDownRight = 12,
        EyeLookInLeft = 13,
        EyeLookInRight = 14,
        EyeLookOutLeft = 15,
        EyeLookOutRight = 16,
        EyeLookUpLeft = 17,
        EyeLookUpRight = 18,
        EyeSquintLeft = 19,
        EyeSquintRight = 20,
        EyeWideLeft = 21,
        EyeWideRight = 22,
        JawForward = 23,
        JawLeft = 24,
        JawOpen = 25,
        JawRight = 26,
        MouthClose = 27,
        MouthDimpleLeft = 28,
        MouthDimpleRight = 29,
        MouthFrownLeft = 30,
        MouthFrownRight = 31,
        MouthFunnel = 32,
        MouthLeft = 33,
        MouthLowerDownLeft = 34,
        MouthLowerDownRight = 35,
        MouthPressLeft = 36,
        MouthPressRight = 37,
        MouthPucker = 38,
        MouthRight = 39,
        MouthRollLower = 40,
        MouthRollUpper = 41,
        MouthShrugLower = 42,
        MouthShrugUpper = 43,
        MouthSmileLeft = 44,
        MouthSmileRight = 45,
        MouthStretchLeft = 46,
        MouthStretchRight = 47,
        MouthUpperUpLeft = 48,
        MouthUpperUpRight = 49,
        NoseSneerLeft = 50,
        NoseSneerRight = 51
    }
}